### PR TITLE
revert #358 and #325

### PR DESCRIPTION
**Pull request by renxida**
Because they broke CI

### CODE REVIEW

**Comment by ScottTodd** [comment]
Keep reverts simple. Remember, _everyone working on the project is broken while the CI is failing_.

**Comment by renxida** [comment]
> Keep reverts simple. Remember, _everyone working on the project is broken while the CI is failing_.

Yup. Had to do this manually since auto revert didnt work for me.

**Review by stbaione — APPROVED** [review]

**Comment by ScottTodd** [comment]
> > Keep reverts simple. Remember, _everyone working on the project is broken while the CI is failing_.
> 
> Yup. Had to do this manually since auto revert didnt work for me.

To revert everything in a range:
```bash
D:\dev\projects\SHARK-Platform (main -> upstream)
λ git checkout -b back-to-green
Switched to a new branch 'back-to-green'

D:\dev\projects\SHARK-Platform (back-to-green)
λ git log --oneline --max-count 10
e4c7c20 (HEAD -> back-to-green, upstream/main, upstream/HEAD, main) Revert "Fix LLM Server Failing CIs" (#364)
4fbc619 Fix LLM Server Failing CIs (#362)
7c39517 Simple KV Cache Access Tests (#325)
f6d54f3 Add Back LLM Server Test (#358)
524e803 Bring requirements.txt iree version back to sync with CI and CMakeLists.txt (#356)
47253d0 Replace commit hash with latest release candidate (#355)
8c9d454 [sharktank] Fix `write_timestep` for direct cache (#354)
fb4be27 Add copyright headers (#352)
a8cd1d8 Fix shortfin gibberish tokens and add cpu_llm_server_test.py (#351)
023d31f [shortfin] Finishes plumbing ProgramIsolation through to the Python API. (#350)

# revert each commit up until 524e803 

D:\dev\projects\SHARK-Platform (back-to-green)
λ git revert 524e803...main
[back-to-green c9cb0ad] Revert "Revert "Fix LLM Server Failing CIs" (#364)"
 1 file changed, 3 insertions(+)
[back-to-green 1e233e1] Revert "Fix LLM Server Failing CIs (#362)"
 1 file changed, 3 deletions(-)
Removing shortfin/tests/invocation/simple_kvcache_access_test.py
[back-to-green 31d0cac] Revert "Simple KV Cache Access Tests (#325)"
 2 files changed, 275 deletions(-)
 delete mode 100644 shortfin/tests/invocation/simple_kvcache_access_test.py
Removing shortfin/tests/apps/llm/cpu_llm_server_test.py
[back-to-green f8c6298] Revert "Add Back LLM Server Test (#358)"
 3 files changed, 2 insertions(+), 176 deletions(-)
 delete mode 100644 shortfin/tests/apps/llm/cpu_llm_server_test.py
```

**Comment by marbre** [comment]
Any specific for manual rollback instead of
```bash
git revert 7c39517db394a5cf5dbef92ae10ae9297faa3d8e
git revert f6d54f3604b4625cdd1c58f3f34d7cab8c34b517
```
This would also revert to lines changed in `shortfin/python/shortfin_apps/llm/components/service.py`.

**Comment by renxida** [comment]
Done! This should have the proper revert commits.

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
